### ISSUE TITLE
Dock keeps crashing

### ISSUE THREAD

**Issue by font-surfer** [briankendall/missionControlFullDesktopBar#1]
After installation the dock keep crashing and relaunching every second. System integrity is off. I have this tweek on macbook and its completly fine. Than I migrated my image to mac mini and this issue appeared.

It happens also in clean user account. Logs attached.

Please fix it, if it is possible. Thanks.

[Dock.txt](https://github.com/briankendall/missionControlFullDesktopBar/files/1065365/Dock.txt)

[crash.txt](https://github.com/briankendall/missionControlFullDesktopBar/files/1065366/crash.txt)

**Comment by briankendall** [comment]
I can see you're running macOS 10.11.6 based off of the crash log. I haven't tested or used missionControlFullDesktopBar in macOS 10.11, and I would recommend against it. The hacky methods it uses to invoke Mission Control with the full desktop bar take advantage of behaviors that are specific to macOS 10.12.

Is there any reason you can't use [forceFullDesktopBar](https://github.com/briankendall/forceFullDesktopBar)? It typically works flawlessly, and it's much more convenient as it just causes Mission Control to always open with the full desktop bar regardless of how it's invoked.
