### ISSUE TITLE
Daemon watch for mission control being launched

### ISSUE THREAD

**Issue by victornpb** [briankendall/missionControlFullDesktopBar#3]
Can't the daemon watch for when the mission control is launched and do it's thing, so you can just leave the daemon running all the time, and trigger the mission control whatever way you already do?

I think it would be easier than having to install better touch tools and override the way you launch mission control.

Idk if there's a reliable/performant way to detect when processes spawn without having to do polling tho.

**Comment by briankendall** [comment]
Mission Control is not actually an application, but rather a part of the Dock. When you trigger it using a mouse, trackpad, or keystroke, the Dock process is responding directly to those events and activating Mission Control. The Mission Control application in the Applications folder does not launch in that case — all it does is send a special signal to the Dock telling it to toggle Mission Control.

If you're interested in a method that essentially "intercepts" anything that triggers Mission Control and changes its behavior, check out my other repo [forceFullDesktopBar](https://github.com/briankendall/forceFullDesktopBar). That one actually modifies the Dock as it's running to persistently change Mission Control's behavior, and currently works with any method of triggering Mission Control, so no need to use BetterTouchTool. It does however require disabling System Integrity Protection.
